SystemUIGoogle: elmyra: CentralSurfacesGoogle -> CentralSurfaces
* QPR2 should use CentralSurfaces instead of CentralSurfacesGoogle
* Logcat:
	java.lang.NoSuchMethodError: No virtual method getKeyguardBottomAreaView()Lcom/android/systemui/statusbar/phone/KeyguardBottomAreaView; in class Lcom/android/systemui/statusbar/phone/CentralSurfacesImpl; or its super classes (declaration of 'com.android.systemui.statusbar.phone.CentralSurfacesImpl' appears in /system_ext/priv-app/SystemUIGoogle/SystemUIGoogle.apk!classes2.dex)

Change-Id: I5a57109f8d6eb5ef5a3510e12d675f77345acb57